build:
  uri: ""
  mode: bootable-jar
  env:
    - name: ARTIFACT_DIR
      value: target
    - name: MAVEN_ARGS_APPEND
      value: "-Popenshift"
deploy:
  env:
    - name: name
      value: Alex in Cloud
    - name: mp.messaging.connector.smallrye-kafka.bootstrap.servers
      value: mail-kafka.alexej-liebenthal-dev.svc.cluster.local:9092
